### ISSUE TITLE
-o option does not work as expected

### ISSUE THREAD

**Issue by rolinh** [gilliek/ghmd#1]
Just try `ghmd -o foo.html foo.md` and inspect the foo.html file: the whole markdown file content is missing from it.

**Comment by rolinh** [comment]
My mistake, it works as expected but I emptied my markdown file by mistake.
Actually, I ran `ghmd -o foo.md foo.html` instead of the other way around and as the foo.html file did not exist at that time, it caused `ghmd` to overwrite `foo.md` with nothing. Maybe it would be a good idea to check for input file existence before outputting something?

**Comment by gilliek** [comment]
I agree, thanks for the idea :)
